// automatically generated by the FlatBuffers compiler, do not modify

package mapbox1.myapplication.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Plugins extends Table {
  public static Plugins getRootAsPlugins(ByteBuffer _bb) { return getRootAsPlugins(_bb, new Plugins()); }
  public static Plugins getRootAsPlugins(ByteBuffer _bb, Plugins obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Plugins __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Plugin plugin(int j) { return plugin(new Plugin(), j); }
  public Plugin plugin(Plugin obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int pluginLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createPlugins(FlatBufferBuilder builder,
      int pluginOffset) {
    builder.startObject(1);
    Plugins.addPlugin(builder, pluginOffset);
    return Plugins.endPlugins(builder);
  }

  public static void startPlugins(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addPlugin(FlatBufferBuilder builder, int pluginOffset) { builder.addOffset(0, pluginOffset, 0); }
  public static int createPluginVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPluginVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endPlugins(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishPluginsBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedPluginsBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

